apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devops
  name: web-devops
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: devops
  type: NodePort
status:
  loadBalancer: {}